In [1]:
import numpy as np

In [6]:
#Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.exp() function to compute the exponential of each element in the array.

arr = np.random.rand(3,3)
np.exp(arr)

array([[2.14299737, 2.67950361, 2.53927811],
       [1.58483046, 2.29260667, 1.20739549],
       [1.68770659, 1.13982724, 1.238438  ]])

In [7]:
#  Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.sin() function to compute the sine of each element in the array.
arr = np.random.rand(4,4)
np.sin(arr)

array([[0.19564786, 0.82408616, 0.59827634, 0.42836782],
       [0.26693026, 0.82841333, 0.09830439, 0.34224754],
       [0.80862665, 0.71969438, 0.55087956, 0.78751848],
       [0.76695615, 0.51748928, 0.64960559, 0.68781672]])

In [8]:
#Create a NumPy array with shape (5,5) and fill it with random numbers. Use the np.log() function to compute the natural logarithm of each element in the array.
arr = np.random.rand(5,5)
np.log(arr)

array([[-0.38616591, -1.33456685, -0.05554907, -0.37501366, -1.03570143],
       [-0.56880457, -0.97899681, -0.20070063, -0.24783464, -0.98068059],
       [-0.46575837, -0.48218194, -0.34017325, -0.14957965, -0.59910337],
       [-0.08816589, -0.60342563, -0.3761972 , -2.85793975, -0.21008296],
       [-0.46386495, -1.69600797, -0.33455839, -0.77421703, -0.13629531]])

In [9]:
#Create a NumPy array with shape (2,2) and fill it with random numbers. Use the np.sqrt() function to compute the square root of each element in the array.
np.sqrt(arr)

array([[0.82441358, 0.51310056, 0.97260763, 0.82902345, 0.59579972],
       [0.75246388, 0.61293376, 0.9045205 , 0.88345288, 0.61241796],
       [0.79224928, 0.78577014, 0.84359174, 0.92793849, 0.74115041],
       [0.95687459, 0.73955042, 0.82853301, 0.23955557, 0.90028718],
       [0.79299967, 0.42826891, 0.84596339, 0.67901741, 0.93412254]])

In [12]:
# Create a NumPy array with shape (6,6) and fill it with random numbers. Use the np.floor() function to round down each element in the array to the nearest integer.
arr = np.random.rand(6,6)*100
np.floor(arr)

array([[ 9., 40., 10.,  3., 16., 88.],
       [23., 61., 19., 40., 92., 12.],
       [62., 63., 36., 97., 94., 45.],
       [46.,  5., 23., 14., 72., 62.],
       [81., 58., 96., 61., 95., 68.],
       [32., 46., 46., 66., 79.,  6.]])

In [13]:
# Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.abs() function to compute the absolute value of each element in the array.
arr = np.random.rand(3,3)
np.abs(arr)

array([[0.55799129, 0.69682127, 0.45318055],
       [0.19479796, 0.61739742, 0.01239621],
       [0.0713875 , 0.60272028, 0.87396632]])

In [17]:
# Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.power() function to raise each element in the array to the power of 2.
arr = np.random.rand(4,4)*100
np.power(arr,2)

array([[ 266.80659103,  220.41036026, 5581.41738109, 3757.0959957 ],
       [1527.48391905, 2628.19450527,  909.4601389 , 8838.89722926],
       [9957.27760332,  282.83058883, 1207.97148405, 2551.33649942],
       [ 143.74509344, 1245.70423654,  191.9358174 , 9611.95574242]])

In [19]:
# Create a NumPy array with 5 random integers between 1 and 10. Use the maximum function to find the largest element in the array.
arr = np.random.randint(1,10,5)
print(arr)
print(max(arr))

[6 1 8 3 8]
8


In [24]:
# Create a NumPy array with 10 random floating-point numbers between 0 and 1. Use the round function to round each element to the nearest integer.
arr = np.random.rand(10)
np.round(arr)

array([1., 1., 0., 0., 0., 1., 1., 1., 1., 1.])

In [29]:
#Create a NumPy array with 7 random integers between 1 and 100. Use the argmax function to find the index of the largest element in the array.
arr = np.random.randint(1,100,7)
print(arr)
np.argmax(arr)

[ 9 88 27 25 68 11 59]


1

In [31]:
#Create two NumPy arrays with the same shape, each filled with random integers between 1 and 10. Use the add function to add the two arrays together element-wise.
arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
np.add(arr1,arr2)

array([16, 18,  5,  5, 12])

In [39]:
# Create a NumPy array with 12 random integers between 0 and 100. Use the clip function to limit the values in the array to a range between 10 and 90.
arr = np.random.randint(0,100,12)
print(arr)
np.clip(arr,10,90)

[63 37  0 27 55 20 73 67 33 25 67 99]


array([63, 37, 10, 27, 55, 20, 73, 67, 33, 25, 67, 90])

In [40]:
# Create a NumPy array with 10 random integers between 0 and 100.
arr = np.random.randint(0,100,10)
arr

array([59, 51, 93, 32, 95, 77,  4, 44, 47, 98])

In [46]:
"""
Use the np.where() function to create a new array with the same shape as the previous one,
where values less than 50 are replaced with -1 and values greater than or equal to 50 are
replaced with 1.
"""
arr1 = np.array([1,2,66,4,57,6])
arr2=np.where(arr1>=50 , 1 , -1)
arr2

array([-1, -1,  1, -1,  1, -1])

In [48]:
# Calculate the mean, median, and standard deviation of the original array.
arr = np.random.randint(0,100,10)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

56.1
57.0
24.10580842867544


In [52]:
# Create a boolean array that is True where the values in the original array are even, and False otherwise.

def is_even(array):
  """Returns a boolean array that is True where the values in the original array are even, and False otherwise."""
  even_array = np.ones_like(array, dtype=bool)
  even_array[array % 2 == 1] = False
  return even_array

if __name__ == "__main__":
      array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
      even_array = is_even(array)
      print(even_array)

[False  True False  True False  True False  True]


In [53]:
# Sort the original array in ascending order.
arr = np.random.randint(0,100,10)
np.sort(arr)

array([ 2,  3, 24, 25, 39, 42, 48, 63, 67, 67])

In [54]:
# Find the unique values in the original array.
np.unique(arr)

array([ 2,  3, 24, 25, 39, 42, 48, 63, 67])

In [60]:
# Use the np.in1d() function to create a boolean array indicating which elements of the original array are also present in a new array with 5 random integers between 0 and 100
test = np.random.randint(0,100,5)
np.in1d(test,arr)

array([False, False, False,  True, False])

In [64]:
# Save the original array to a text file named "my_array.txt" using the np.savetxt() function.
np.savetxt('my_array.txt',arr)