In [2]:
import numpy as np

In [3]:
arr1 = np.array([[4,3,2,5],[8,7,2,9]])
arr1

array([[4, 3, 2, 5],
       [8, 7, 2, 9]])

In [4]:
 #Array Multiplication: Element by element
arr1*arr1

array([[16,  9,  4, 25],
       [64, 49,  4, 81]])

In [6]:
 #Scaler operation
arr1+4

array([[ 8,  7,  6,  9],
       [12, 11,  6, 13]])

In [8]:
#Exponencial operation
arr1**3

array([[ 64,  27,   8, 125],
       [512, 343,   8, 729]], dtype=int32)

In [9]:
#Lets transpose
arr1.T

array([[4, 8],
       [3, 7],
       [2, 2],
       [5, 9]])

In [10]:
 # Taking dot product of matrices
A=np.array([[1,2,3],[4,5,6]])
print(A)
print('\n')
B=np.array([[7,8],[9,10],[11,12]])
print(B)
print('\n')
np.dot(A,B)

[[1 2 3]
 [4 5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]




array([[ 58,  64],
       [139, 154]])