In [1]:
import numpy as np

In [2]:
#create array 0,15
arr=np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
 #Size of the array
arr.shape

(16,)

In [4]:
#value at index 5
arr[5]

5

In [5]:
#values at range index. Start at indx=1 end at indx=4
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#value at range index
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
#Set a value at range
arr[0:2]=100
arr

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [8]:
#slices of the array
slice_of_arr = arr[0:7]
slice_of_arr

array([100, 100,   2,   3,   4,   5,   6])

In [10]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99, 99])

In [11]:
arr

array([99, 99, 99, 99, 99, 99, 99,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
 #To copy a sclice of the array
arr_copy = arr[6:9].copy()
arr_copy

array([99,  7,  8])

In [13]:
arr_copy[:]=0
arr_copy

array([0, 0, 0])

In [14]:
arr

array([99, 99, 99, 99, 99, 99, 99,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
 #indexing in 2D Array
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
#print a row index 0
arr_2d[0] # arr_2d[0,:]

array([ 5, 10, 15])

In [17]:
#print a column index 1
arr_2d[:,1]

array([10, 25, 40])

In [41]:
#indexing in 2D Array
#Individual element value
arr_2d[1][2]

30

In [42]:
arr_2d[:3,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [44]:
arr_2d[:3, ::2] # all rows, every other column,2 steps

array([[ 5, 15],
       [20, 30],
       [35, 45]])

In [45]:
#create 3x4 matrix using arange function
grid = np.arange(1, 13).reshape((3, 4))
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
 #Concatenation of arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [47]:
#Splitting Arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) #split at index 3 &5
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [48]:
 #Splitting 2D Array
#Horizontal Split
grid = np.arange(16).reshape((4, 4))
print(grid)
print("\n")
upper, lower = np.vsplit(grid, [2]) #give the index
print(upper)
print("\n")
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [21]:
arr = np.array([[1,2],[3,4]])
arr*2

array([[2, 4],
       [6, 8]])

In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr +5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [24]:
arr = np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12],[13,14,15,16]])
arr -10

array([[-9, -8, -7,  0],
       [-6, -5, -4,  1],
       [-3, -2, -1,  2],
       [ 3,  4,  5,  6]])

In [26]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
arr/2

array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5]])

In [29]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30],[31,32,33,34,35,36]])
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
        3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        , 4.12310563,
        4.24264069],
       [4.35889894, 4.47213595, 4.58257569, 4.69041576, 4.79583152,
        4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
        5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        ]])

In [35]:
a = np.array([[2, 3],
              [5, 9]])
a = a.T
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[18, 12],
       [30, 21]])

In [37]:
vector_a = np.array([[1, 4, 24], [5, 6, 7],[12 , 13 , 20]])
vector_b = np.array([[2, 4, 12], [5, 2, 3], [45 , 23, 11]])
 
product = np.dot(vector_a, vector_b)
print("Dot Product  : \n", product)
 
product = np.dot(vector_b, vector_a)
print("\nDot Product  : \n", product)

Dot Product  : 
 [[1102  564  288]
 [ 355  193  155]
 [ 989  534  403]]

Dot Product  : 
 [[ 166  188  316]
 [  51   71  194]
 [ 292  461 1461]]


In [38]:
vector_a = np.array([[1, 4, 24], 
                     [5, 6, 7]])
vector_b = np.array([[2, 4],
                     [5, 2], 
                     [45 , 23]])
np.matmul(vector_a,vector_b)

array([[1102,  564],
       [ 355,  193]])

In [40]:
vector_a = np.array([[1, 4, 24], 
                     [5, 6, 7]])
vector_b = np.array([[2, 4],
                     [5, 2], 
                     [45 , 23]])
np.dot(vector_a,vector_b)

array([[1102,  564],
       [ 355,  193]])

In [49]:
arr = [0,1,2,3,4,5,6,7,8,9]
arr[2]

2

In [50]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr[1][0]

4

In [58]:
import numpy as np

rows = 4
cols = 4

arr = np.random.rand(rows, cols)
arr

array([[0.32107649, 0.86910381, 0.31372545, 0.54852039],
       [0.66163393, 0.97920237, 0.89429838, 0.31479827],
       [0.26090234, 0.86297462, 0.43285155, 0.8161542 ],
       [0.21813445, 0.82818097, 0.86232169, 0.02992098]])

In [59]:
arr[:2,2:]

array([[0.31372545, 0.54852039],
       [0.89429838, 0.31479827]])

In [64]:
arr = [0,1,2,3,4,5,6,7,8,9]
c_arr = arr.copy()
c_arr[0:3]

[0, 1, 2]

In [65]:
rows = 3
cols = 3

arr = np.random.rand(rows, cols)
arr

array([[0.1064701 , 0.7493227 , 0.23323035],
       [0.46790573, 0.0291675 , 0.32857286],
       [0.73422039, 0.28377549, 0.30592375]])

In [66]:
c_arr = arr.copy()
c_arr[:2,:2]

array([[0.1064701 , 0.7493227 ],
       [0.46790573, 0.0291675 ]])

In [70]:
arr = [1,2,3,4,5,6,7,8,9]
np.reshape(arr,[3,3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
rows = 4
cols = 4

arr = np.random.rand(rows, cols)
arr

array([[0.77121246, 0.59924257, 0.1732238 , 0.13870337],
       [0.86356902, 0.21236251, 0.35373506, 0.84455008],
       [0.36452867, 0.03130029, 0.65147561, 0.88457733],
       [0.21027913, 0.65714877, 0.77083393, 0.83622778]])

In [78]:
np.reshape(arr,16)

array([0.77121246, 0.59924257, 0.1732238 , 0.13870337, 0.86356902,
       0.21236251, 0.35373506, 0.84455008, 0.36452867, 0.03130029,
       0.65147561, 0.88457733, 0.21027913, 0.65714877, 0.77083393,
       0.83622778])

In [83]:
arr1 = np.array([0,1,2,3,4])
arr2 = np.array([0,1,2,3,4])
arr = np.concatenate((arr1,arr2),axis=0)
arr

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [85]:
arr1 = np.array([[0,10],[3,4]])
arr2 = np.array([[0,1,3],[2,3,4]])
arr = np.concatenate((arr1,arr2),axis=1)
arr

array([[ 0, 10,  0,  1,  3],
       [ 3,  4,  2,  3,  4]])

In [87]:
arr1 = np.array([[0,10],[3,4]])
arr2 = np.array([[0,1],[2,3],[7,5]])
arr = np.concatenate((arr1,arr2),axis=0)
arr

array([[ 0, 10],
       [ 3,  4],
       [ 0,  1],
       [ 2,  3],
       [ 7,  5]])

In [91]:
arr = [1,2,3,4,5,6,7,8,9]
for i in arr:
    if arr[i] %2 != 0:
        arr[i] = 0
arr

[0, 2, 0, 4, 0, 6, 0, 8, 0]

In [92]:
rows = 3
cols = 3

arr = np.random.rand(rows, cols)
arr

array([[0.25567973, 0.86645516, 0.20152709],
       [0.88527231, 0.07756495, 0.72276545],
       [0.26470529, 0.79911023, 0.9733031 ]])

In [93]:
arr[:1,:] = 0
arr

array([[0.        , 0.        , 0.        ],
       [0.88527231, 0.07756495, 0.72276545],
       [0.26470529, 0.79911023, 0.9733031 ]])

In [94]:
rows = 3
cols = 3

arr = np.random.rand(rows, cols)
arr

array([[0.07064541, 0.79534343, 0.89184279],
       [0.17382195, 0.49508774, 0.53022009],
       [0.32658066, 0.19840545, 0.5361268 ]])

In [96]:
arr[:,2:] = 0
arr

array([[0.07064541, 0.79534343, 0.        ],
       [0.17382195, 0.49508774, 0.        ],
       [0.32658066, 0.19840545, 0.        ]])

In [102]:
arr = [1,2,3,4,5,6,7,8,9]
ar = arr.copy()
for i in ar:
    print(i*2,end=" ")

2 4 6 8 10 12 14 16 18 

In [103]:
from numpy.random import randn
arr = randn(5,5)
arr

array([[-1.281175  ,  0.58435762, -0.32324163, -2.74699793, -0.24348447],
       [-0.2572571 ,  0.36987736, -1.40962998, -0.5644403 ,  0.14172199],
       [ 2.26858733, -0.7171223 ,  0.68439594,  3.37943491, -0.51757784],
       [-0.86723443,  0.77055203, -0.14634385, -0.75277692, -1.10515349],
       [ 0.0848651 , -0.92205089, -1.23570577, -0.34571089, -0.08627749]])

In [104]:
#mean = 2 ,std = 1.5,randn(5,5) -> z_scoresS
arr = 2+1.5*randn(5,5)
arr

array([[ 0.78578283,  3.19858494,  5.14472712,  1.94573394,  2.74134168],
       [ 1.18322457,  3.79311889,  2.13170447, -0.27724193, -0.17666737],
       [ 3.11086946,  2.98339234, -1.48974389,  3.7507816 ,  0.5838337 ],
       [ 3.37809305,  2.61348569,  1.69529733,  3.23335244,  3.22930422],
       [ 3.26550928,  2.34435567,  0.72681333,  1.80259651,  1.42299984]])