In [1]:
import numpy as np #adding numpy lib

In [3]:
l1 = [5,3,6,8,9] #normal list

In [5]:
arr1 = np.array(l1) #creating 1D array from list
arr1

array([5, 3, 6, 8, 9])

In [6]:
l2 = [44,13,45,64,22]
l2

[44, 13, 45, 64, 22]

In [7]:
l = [l1,l2] #combining two lists
l

[[5, 3, 6, 8, 9], [44, 13, 45, 64, 22]]

In [8]:
array_2D = np.array(l) #2D array
array_2D

array([[ 5,  3,  6,  8,  9],
       [44, 13, 45, 64, 22]])

In [9]:
array_2D.shape #it contains 2 rows and five colomns

(2, 5)

In [10]:
array_2D.dtype

dtype('int32')

In [11]:
np.zeros(4,'int') #Special Array (Zero), check without data type

array([0, 0, 0, 0])

In [12]:
np.ones(4) #Special Array (Ones), check without data type

array([1., 1., 1., 1.])

In [13]:
np.ones([3,3])    #2D Array with ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.zeros(4)
np.empty(4) #Special Array (Empty)

array([0., 0., 0., 0.])

In [20]:
np.eye(4) ##Special Array (Identity, nxn) Array A*I=A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
np.arange(3,70,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69])

In [25]:
np.linspace(2, 30, 3)  #returns evenly spaced numbers over a specified between two limits.

array([ 2., 16., 30.])

In [26]:
l1 = [0,1,2,3,4,5,6,7,8,9]
arr1 = np.array(l1) #creating 1D array from list 0 to 9
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [51]:
integer_array = np.random.randint(0, 100, 10)
integer_array

array([74,  9, 78, 82, 14, 50, 20, 95,  7, 36])

In [52]:
float_array = np.random.rand(10)
float_array

array([0.16352627, 0.16055405, 0.89003088, 0.16416974, 0.95642795,
       0.85365588, 0.70747123, 0.37449803, 0.57823834, 0.58868626])

In [53]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])